#!/bin/bash

#
# Typically run this script as:
#
#  nohup ./extract-script &
#


#
#  Input OSM-file
#
IN_FILE="/mnt/history-latest.osm.pbf"
OUT_DIR="/datadrive/osm-out/"

#
#  Store system and file characteristics
#  
sudo lshw > ${OUT_DIR}run-system-info
stat --printf "Filename: %n\nFile size: %s\n MD5: \n" $IN_FILE > ${OUT_DIR}run-file-info
touch ${OUT_DIR}run-timing-start-md5
md5sum $IN_FILE >> ${OUT_DIR}run-file-info

#
#  Extract nodes, ways, and relations:
#
touch ${OUT_DIR}run-timing-start-nodes
node extract-amenities.js node $IN_FILE > ${OUT_DIR}full-nodes.txt

touch ${OUT_DIR}run-timing-start-ways
node extract-amenities.js way $IN_FILE > ${OUT_DIR}full-ways.txt

touch ${OUT_DIR}run-timing-start-relations
node extract-amenities.js relation $IN_FILE > ${OUT_DIR}full-relations.txt

touch ${OUT_DIR}run-timing-script-done

##
